steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '--build-arg'
      - 'VITE_GOOGLE_MAPS_KEY=${_VITE_GOOGLE_MAPS_KEY}'
      - '-t'
      - '${_IMAGE}'
      - '.'
images:
  - '${_IMAGE}'
timeout: 1200s
