analyst_services: []

other_services:
  object_manager: True
  query_manager: True
  semantic_manager: True

sql_statement_permissions:
  - Select: True
  - Describe: True
  - Use: True
  - Create: False
  - Alter: False
  - Insert: False
  - Update: False
  - Delete: False
  - Drop: False
  - TruncateTable: False
  - Grant: False
  - Command: False
  - Unknown: False
