"""Unit tests for Snowflake client: query result mapping, fallback loading."""

import json
from pathlib import Path
from unittest.mock import MagicMock, patch

import pytest

from app.snowflake_client import load_fallback_data, query_mine_for_subregion


MOCK_ROW = {
    "MINE_NAME": "Bailey Mine",
    "MINE_OPERATOR": "Consol Pennsylvania Coal Company LLC",
    "MINE_COUNTY": "Greene",
    "MINE_STATE": "PA",
    "MINE_TYPE": "Underground",
    "MINE_LAT": 39.9175,
    "MINE_LON": -80.471944,
    "PLANT_NAME": "Cross",
    "PLANT_OPERATOR": "South Carolina PSA",
    "PLANT_LAT": 33.371506,
    "PLANT_LON": -80.113235,
    "TOTAL_TONS": 1247001,
    "TONS_YEAR": 2024,
}


class TestQueryMineForSubregion:
    def _mock_connection(self, rows):
        mock_cursor = MagicMock()
        mock_cursor.fetchone.return_value = rows[0] if rows else None
        mock_conn = MagicMock()
        mock_conn.cursor.return_value = mock_cursor
        return mock_conn

    @patch("app.snowflake_client._get_connection")
    def test_valid_result_maps_fields(self, mock_get_conn):
        mock_get_conn.return_value = self._mock_connection([MOCK_ROW])
        result = query_mine_for_subregion("SRVC")

        assert result["mine"] == "Bailey Mine"
        assert result["mine_operator"] == "Consol Pennsylvania Coal Company LLC"
        assert result["mine_county"] == "Greene"
        assert result["mine_state"] == "PA"
        assert result["mine_type"] == "Underground"
        assert result["mine_coords"] == [39.9175, -80.471944]
        assert result["plant"] == "Cross"
        assert result["plant_operator"] == "South Carolina PSA"
        assert result["plant_coords"] == [33.371506, -80.113235]
        assert result["tons"] == 1247001.0
        assert result["tons_year"] == 2024

    @patch("app.snowflake_client._get_connection")
    def test_no_rows_returns_none(self, mock_get_conn):
        mock_get_conn.return_value = self._mock_connection([])
        result = query_mine_for_subregion("NONEXISTENT")
        assert result is None

    @patch("app.snowflake_client._get_connection")
    def test_subregion_uppercased(self, mock_get_conn):
        mock_conn = self._mock_connection([MOCK_ROW])
        mock_get_conn.return_value = mock_conn
        query_mine_for_subregion("srvc")
        call_args = mock_conn.cursor().execute.call_args
        assert call_args[0][1]["subregion_id"] == "SRVC"

    @patch("app.snowflake_client._get_connection")
    def test_connection_closed_on_success(self, mock_get_conn):
        mock_conn = self._mock_connection([MOCK_ROW])
        mock_get_conn.return_value = mock_conn
        query_mine_for_subregion("SRVC")
        mock_conn.close.assert_called_once()

    @patch("app.snowflake_client._get_connection")
    def test_connection_closed_on_error(self, mock_get_conn):
        mock_conn = MagicMock()
        mock_conn.cursor.return_value.execute.side_effect = Exception("DB error")
        mock_get_conn.return_value = mock_conn

        with pytest.raises(Exception, match="DB error"):
            query_mine_for_subregion("SRVC")

        mock_conn.close.assert_called_once()

    @patch("app.snowflake_client._get_connection")
    def test_tons_converted_to_float(self, mock_get_conn):
        row = {**MOCK_ROW, "TOTAL_TONS": 5000000}
        mock_get_conn.return_value = self._mock_connection([row])
        result = query_mine_for_subregion("SRVC")
        assert isinstance(result["tons"], float)

    @patch("app.snowflake_client._get_connection")
    def test_coords_are_two_element_lists(self, mock_get_conn):
        mock_get_conn.return_value = self._mock_connection([MOCK_ROW])
        result = query_mine_for_subregion("SRVC")
        assert len(result["mine_coords"]) == 2
        assert len(result["plant_coords"]) == 2


class TestLoadFallbackData:
    def test_existing_fallback_file_loads(self):
        # SRVC.json was generated by scripts/generate_fallbacks.py
        result = load_fallback_data("SRVC")
        if result is not None:
            assert "mine" in result
            assert "tons" in result

    def test_missing_fallback_returns_none(self):
        result = load_fallback_data("DEFINITELY_NOT_A_REAL_SUBREGION_XYZ")
        assert result is None

    def test_case_insensitive_lookup(self):
        # load_fallback_data uppercases the subregion_id
        result_upper = load_fallback_data("SRVC")
        result_lower = load_fallback_data("srvc")
        assert result_upper == result_lower
